config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end




  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path(@dose.cocktail)
  end



  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end

  end

  private

  def review_params
    params.require(:review).permit(:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<%= render "shared/card" %>
<%# <%= link_to "Add dose", new_cocktail_dose_path(cocktail) %>

app/views/cocktails/new.html.erb
<div class="container-new">

  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name%>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn btn-dark" %>
  <% end %>

</div>

app/views/cocktails/show.html.erb
<div class="container-show">
  <div class="image">
    <%= cl_image_tag @cocktail.photo.key, height: 500, width: 600, crop: :fill %>
    <% if @cocktail.reviews.empty? %>
      <div id="new-review">
        <%= link_to 'New Review', new_cocktail_review_path(@cocktail) %>
      </div>
    <% else %>
      <div class="star-review">
        <ul>
          <li><i class="fas fa-star"></i></li>
          <li><i class="far fa-star"></i></li>
        </ul>
      </div>
    <% end %>
    </div>
    <div class="cocktail-text">
      <div class="cocktail-description">
        <h1><%= @cocktail.name %></h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe unde enim velit cum quisquam natus perspiciatis quidem porro ad dolorum? Velit fugit earum neque ullam beatae eaque officiis, repellat maxime?</p>
      </div>
      <div class="cocktail-ingredients">
          <h4>Ingredients</h4>
          <div class="ingredients-box">
            <ul>
              <% @cocktail.doses.each do |dose| %>
              <div class="ingredient-description">
                <li><%= dose.description %> <%= dose.ingredient.name %> </li>
                  <%= link_to "delete",
                    dose_path(dose),
                    method: :delete, data: { confirm: "Are you sure?" }, class: "btn-remove" %></li>
              </div>
              <% end %>
                <%= link_to "", new_cocktail_dose_path(@cocktail), class: "fas fa-plus"%>
            </ul>

          </div>
      </div>
      <div class="cocktail-preparation">
        <h5>Preparation</h5>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti consequuntur hic autem eveniet reprehenderit, eaque in fugiat alias, voluptas nesciunt beatae at recusandae error quae vero iste ipsam magni repellat!</p>
      </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container-new">

  <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit class: "btn btn-dark" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<h3>Add a review</h3>
<%= simple_form_for([@cocktail, @review]) do |f| %>
  <%= f.input :rating, collections: 0..5 %>
  <%= f.submit class: "btn btn-dark" %>
<% end %>

app/views/reviews/new.js.erb
$('#new-review a').parent().html('<%= j render 'new' %>')

app/views/shared/_card.html.erb
<div class="container-card">
  <% @cocktails.each do |cocktail|%>
    <div class="card-category"
      style="background-image: url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
      <%= link_to cocktail.name.capitalize, cocktail_path(cocktail), class: "text-white text-decoration-none" %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="container-navbar">
  <nav class="navbar">
    <%= link_to 'Mister Cocktail', root_path, class: 'navbar-brand' %>
    <%= link_to '', root_path, class: "fas fa-glass-cheers" %>
    <%= link_to 'Add cocktail', new_cocktail_path, class: 'btn-white' %>
  </nav>
</div>